name: Build and Release

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6
    
    - name: Generate Version Tag
      id: version
      run: echo "tag=v$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_OUTPUT
    
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26.x'
        
    - name: Build Backend AMD64
      run: cd backend && GOOS=linux GOARCH=amd64 go build -o ../mtn-backend-amd64 ./cmd/server
      
    - name: Build Backend ARM64
      run: cd backend && GOOS=linux GOARCH=arm64 go build -o ../mtn-backend-arm64 ./cmd/server

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
